config/routes.rb
Rails.application.routes.draw do
  match 'access_token_state', to: 'access#token_state', via: [:post]
  match 'session_sign_in',    to: 'sessions#sign_in',   via: [:post]

  root to: 'sessions#index'
end

app/models/access.rb
class Access
  include ActiveModel::Model
  include Auth

  attr_accessor :access_token,
    :expires_in,
    :token_type

  def get_token_state
    connect_introspect(access_token)
  end
end

app/models/user.rb
class User
  include ActiveModel::Model
  include Auth

  attr_accessor :client_id,
    :grant_type,
    :username,
    :password,
    :client_secret,
    :scope

  def sign_in
    connect_token(self.as_json)
  end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def token_state
    @access      = Access.new(access_params)
    @token_state = @access.get_token_state
    @error       = @token_state[:error] if @token_state.key?(:error)

    respond_to do |f|
      f.js { render @error.blank? ? 'access/token_state' : 'access/error' }
    end
  end

  def access_params
    params
      .require(:access)
      .permit(
        :access_token,
        :expires_in,
        :token_type
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    @user = User.new
  end

  def sign_in
    @user   = User.new(user_params).sign_in
    @error  = @user[:error] if @user.key?(:error)
    @access = Access.new(@user) if @error.blank?

    respond_to do |f|
      f.js { render @error.blank? ? 'access/index' : 'error' }
    end
  end

  private

  def user_params
    params
      .require(:user)
      .permit(
        :client_id,
        :grant_type,
        :username,
        :password,
        :client_secret,
        :scope
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/access/_form.html.erb
<div class="form">
  <%= simple_form_for access, url: access_token_state_path, remote: true,  html: { class: 'form-horizontal' } do |f| %>
    <%= f.input :access_token, readonly: true %>
    <%= f.input :expires_in, readonly: true %>
    <%= f.input :token_type, readonly: true %>
    <%= f.button :submit, 'Check Token', data: { disable_with: 'Processing...' }, class: 'btn btn-primary'  %>
  <% end %>
</div>

app/views/access/_token_state.html.erb
<div class="alert alert-info access-alert">
  <pre><%= JSON.pretty_generate(token_state) %></pre>
</div>

app/views/access/error.js.erb
$('.js-access-token-state').hide();
$('.js-error').show().html(
  "<%= escape_javascript render(partial: 'shared/error', locals: { error: @error }) %>"
)

app/views/access/index.js.erb
$('.js-access').show().html(
  "<%= escape_javascript render(partial: 'access/form', locals: { access: @access }) %>"
);

app/views/access/token_state.js.erb
$('.js-error').hide();
$('.js-access-token-state').show().html(
  "<%= escape_javascript render(partial: 'token_state', locals: { token_state: @token_state }) %>"
)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuthTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error.html.erb
<div class="alert alert-danger">
  <%= strip_tags error %>
</div>